AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Security/YAMLLoad:
  Enabled: false
